services:
  catalog.api:
    build: 
         context: .
         dockerfile: C:\Users\User\source\repos\Module6_HW1\Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Develop
        - ASPNETCORE_URLS=http://+:5000
    ports:
    - 5000:5000    
  nginx:
    image: nginx:latest
    ports:
    - 80:80